### ISSUE TITLE
About the simulation model

### ISSUE THREAD

**Issue by sbyebss** [szebedy/autonomous-drone#13]
Hello! @szebedy I think the 3D model in the Gazebo is not the intel drone's model. Maybe this is ok for simulation. But I am wondering whether this would cause some problem when applying the code in real intel drone in the real world? I am also wondering why you didn't use the intel 3D model? Thank you!

**Comment by sbyebss** [comment]
And I am wondering how you obtain the dynamics parameters of the Intel RTF drone? Like the mass and moment of inertia?

**Comment by szebedy** [comment]
Hi @sbyebss, the simulated drone is a model of the 3DR Iris. I didn't use the Intel RTF model because I did not have time to find/create it. My application ran excellent on the real Intel RTF drone, but I can imagine that in a more dynamic scenario this could make a difference. 

I'm not sure how you obtain the dynamic parameters, but I'm sure there are reliable methods for that.

**Comment by sbyebss** [comment]
Hi! @szebedy 
I see. Thank you for your reply. It seems that these dynamics parameters don't influence a lot on the control system design. I will try to use this model first as well. Thank you!
